/crazyflie_server:
  ros__parameters:
    warnings:
      frequency: 1.0 # report/run checks once per second
      motion_capture:
        warning_if_rate_outside: [80.0, 120.0]
    firmware_params:
      query_all_values_on_connect: False
    # simulation related
    sim:
      max_dt: 0 #0.1              # artificially limit the step() function (set to 0 to disable)
      backend: np                 # see backend folder for a list 
      visualizations:             # see visualization folder for a list
        rviz:
          enabled: true
        pdf:
          enabled: false
          output_file: "result.pdf"
        record_states:
          enabled: false
          output_dir: "state_info"
          logging_time: 0.2  # how many seconds to leave between logs
          file_formats: ["csv", "np"] # csv, np
        blender:
          enabled: false
          fps: 1           # frames per second
          cycle_bg: false  # if true, pictures will cycle through different environemt background images (useful for synthetic image generation). Otherwise a single environment background image will be used
          cf_cameras:      # names of crazyflies with cameras on them if enabled in `crazyflies.yaml`
            cf231:
              calibration:
                tvec: [0,0,0]
                rvec: [1.2092,-1.2092,1.2092]   # 0 deg tilt (cameras looks in front of crazyflie)
            cf5:
              calibration:
                tvec: [0,0,0]
                rvec: [ 0.61394313, -0.61394313,  1.48218982]   # 45 deg tilt
      controller: mellinger # none, pid, mellinger
