/teleop:
  ros__parameters:
    frequency: 100  # set to 0, to disable manual flight modes
    mode: "cmd_vel_world" # one of cmd_rpy, cmd_vel_world
    cmd_rpy:
      roll:
        axis: 5
        max: 30.0 # deg
        deadband: 0.0
      pitch:
        axis: 4
        max: 30.0 # deg
        deadband: 0.0
      yawrate:
        axis: 1
        max: 200.0 # deg/s
        deadband: 5.0 # deg/s
      thrust:
        axis: 2
        max: 60000.0 # PWM
        deadband: 0.0
    cmd_vel_world:
      x_velocity:
        axis: 5
        max: 0.5 # m/s
        deadband: 0.1 # m/s
      y_velocity:
        axis: 4
        max: 0.5 # m/s
        deadband: 0.1 # m/s
      z_velocity:
        axis: 2
        max: 0.5 # m/s
        deadband: 0.1 # m/s
      yaw_velocity:
        axis: 1
        max: 0.5 # rad/s
        deadband: 0.1 # rad/s
      # workspace limits
      x_limit: [-1.0, 1.0] # m
      y_limit: [-1.0, 1.0] # m
      z_limit: [0.0, 2.5] # m
    initial_position:
      x: 0.0
      y: 0.0
      z: 0.10
    auto_yaw_rate: 0.0 # rad/s, use 0.0 for manual yaw control


